# Generated by Django 3.0.7 on 2020-06-14 21:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=30)),
                ('subslist', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
